Repository cpp-pm/hunter, pull requests merged in 2022-09, with the labels that each got.

#611 Update RocksDB to 7.5.3
  cmake/configs/default.cmake
  cmake/projects/rocksdb/hunter.cmake
Labels: package:update

#609 Fix CMAKE_IOS_INSTALL_COMBINED on Xcode 12+
  cmake/schemes/git_tag_cmake.cmake.in
  cmake/schemes/url_sha1_cmake.cmake.in
Labels: bug

#612 CI: Boost: update matrix.json to match general workflow
  cmake/projects/Boost/ci/matrix.json
Labels: infrastructure

#599 Boost: update to v1.79.0
  cmake/configs/default.cmake
  cmake/projects/Boost/hunter.cmake
Labels: package:update
