Repository cpp-pm/hunter, pull requests merged in 2023-10, with the labels that each got.

#695 CI: remove macos-10.15 jobs as the macos-10.15 runners are removed
  .github/workflows/ci/matrix.json
  cmake/projects/Boost/ci/matrix.json
  cmake/projects/filament/ci/matrix.json
Labels: infrastructure

#693 ZLIB: update to version v1.3.0-p0
  cmake/configs/default.cmake
  cmake/projects/ZLIB/hunter.cmake
Labels: package:update

#692 miniz: update to v3.0.2
  cmake/configs/default.cmake
  cmake/projects/miniz/hunter.cmake
Labels: package:update

#697 Update fmt package to 10.1.1
  cmake/configs/default.cmake
  cmake/projects/fmt/hunter.cmake
Labels: package:update

#702 SuiteSparse: update to 1.8.0 / 5.4.0-2
  cmake/configs/default.cmake
  cmake/projects/SuiteSparse/hunter.cmake
Labels: package:update

#696 OpenCV, Extra, ippicv: update to v4.8.1-p0
  cmake/configs/default.cmake
  cmake/projects/OpenCV-Extra/hunter.cmake
  cmake/projects/OpenCV/hunter.cmake
  cmake/projects/ippicv/hunter.cmake
  docs/packages/pkg/OpenCV-Extra.rst
  docs/packages/pkg/ippicv.rst
  examples/OpenCV-Extra/foo.cpp
Labels: package:update

#703 ceres-solver: update to v2.2.0-p0 and fix examples
  cmake/configs/default.cmake
  cmake/projects/ceres-solver/hunter.cmake
  examples/ceres-solver-suitesparse-dynLAPACK/config.cmake
  examples/ceres-solver-suitesparse/CMakeLists.txt
  examples/ceres-solver-suitesparse/config.cmake
Labels: package:update

#704 Eigen: explicitly disable Fortran usage
  cmake/projects/Eigen/hunter.cmake
Labels: bug, package:update

#719 glog: add version 0.6.0 and disable new dependencies
  cmake/configs/default.cmake
  cmake/projects/glog/hunter.cmake
Labels: package:update

#720 ceres-solver: update to v2.2.0-p1
  cmake/configs/default.cmake
  cmake/projects/ceres-solver/hunter.cmake
Labels: package:update
