Repository cpp-pm/hunter, pull requests merged in 2025-06, with the labels that each got.

#644 update msgpack to v4.1.3
  cmake/configs/default.cmake
  cmake/projects/msgpack/hunter.cmake
  docs/packages/pkg/msgpack.rst
  examples/msgpack/CMakeLists.txt
Labels: package:update

#304 Update civetweb to v1.13-p0
  cmake/configs/default.cmake
  cmake/projects/civetweb/hunter.cmake
Labels: package:update

#561 docs: update URL to tar file for boost-components documentation
  docs/quick-start/boost-components.rst
Labels: documentation, needs-info

#785 fix link-all.py with high CPU count and little files
  scripts/link-all.py
Labels: bug

#786 set_matrix: simplify regex, fix typos
  .github/workflows/set_matrix.py
Labels: infrastructure

#792 OpenBLAS: silence warnings
  cmake/projects/OpenBLAS/hunter.cmake
Labels: enhancement
